"""test migrate

Revision ID: 1e4fea11df4a
Revises: ee722ce19a68
Create Date: 2024-01-20 15:34:11.734013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4fea11df4a'
down_revision: Union[str, None] = 'ee722ce19a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('test', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_test'), 'tasks', ['test'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_test'), table_name='tasks')
    op.drop_column('tasks', 'test')
    # ### end Alembic commands ###
