"""i

Revision ID: 92ef6f7d5ea1
Revises: 5c7fe7b4c44f
Create Date: 2024-01-29 18:21:09.503979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ef6f7d5ea1'
down_revision: Union[str, None] = '5c7fe7b4c44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_userss_id', table_name='userss')
    op.drop_table('userss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='userss_pkey')
    )
    op.create_index('ix_userss_id', 'userss', ['id'], unique=False)
    # ### end Alembic commands ###
